#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 112
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 48
#define ALIAS_COUNT 0
#define TOKEN_COUNT 20
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define PRODUCTION_ID_COUNT 1

enum ts_symbol_identifiers {
  anon_sym_COLON_EQ = 1,
  anon_sym_COLON = 2,
  anon_sym_AMP = 3,
  anon_sym_PIPE = 4,
  anon_sym_BANG = 5,
  anon_sym_QMARK = 6,
  anon_sym_LPAREN = 7,
  anon_sym_RPAREN = 8,
  anon_sym_LBRACK = 9,
  anon_sym_RBRACK = 10,
  anon_sym_LBRACE = 11,
  anon_sym_RBRACE = 12,
  anon_sym_SEMI = 13,
  sym_regex = 14,
  anon_sym_EQ = 15,
  sym_relation_operator = 16,
  anon_sym_TILDE = 17,
  anon_sym_AT = 18,
  sym_identifier = 19,
  sym_source_file = 20,
  sym_pattern_definition = 21,
  sym_pattern_name = 22,
  sym_query = 23,
  sym_expression = 24,
  sym_conjunction = 25,
  sym_disjunction = 26,
  sym_sequence = 27,
  sym_term = 28,
  sym_postfix_term = 29,
  sym_primary_term = 30,
  sym_node_pattern = 31,
  sym_attributes = 32,
  sym_attribute = 33,
  sym_key = 34,
  sym_value = 35,
  sym_node_name = 36,
  sym_name = 37,
  sym_relation_pattern = 38,
  sym_relation_label = 39,
  sym_edge_name = 40,
  sym_pattern_reference = 41,
  aux_sym_source_file_repeat1 = 42,
  aux_sym_query_repeat1 = 43,
  aux_sym_conjunction_repeat1 = 44,
  aux_sym_disjunction_repeat1 = 45,
  aux_sym_sequence_repeat1 = 46,
  aux_sym_attributes_repeat1 = 47,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_COLON_EQ] = ":=",
  [anon_sym_COLON] = ":",
  [anon_sym_AMP] = "&",
  [anon_sym_PIPE] = "|",
  [anon_sym_BANG] = "!",
  [anon_sym_QMARK] = "\?",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_SEMI] = ";",
  [sym_regex] = "regex",
  [anon_sym_EQ] = "=",
  [sym_relation_operator] = "relation_operator",
  [anon_sym_TILDE] = "~",
  [anon_sym_AT] = "@",
  [sym_identifier] = "identifier",
  [sym_source_file] = "source_file",
  [sym_pattern_definition] = "pattern_definition",
  [sym_pattern_name] = "pattern_name",
  [sym_query] = "query",
  [sym_expression] = "expression",
  [sym_conjunction] = "conjunction",
  [sym_disjunction] = "disjunction",
  [sym_sequence] = "sequence",
  [sym_term] = "term",
  [sym_postfix_term] = "postfix_term",
  [sym_primary_term] = "primary_term",
  [sym_node_pattern] = "node_pattern",
  [sym_attributes] = "attributes",
  [sym_attribute] = "attribute",
  [sym_key] = "key",
  [sym_value] = "value",
  [sym_node_name] = "node_name",
  [sym_name] = "name",
  [sym_relation_pattern] = "relation_pattern",
  [sym_relation_label] = "relation_label",
  [sym_edge_name] = "edge_name",
  [sym_pattern_reference] = "pattern_reference",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_query_repeat1] = "query_repeat1",
  [aux_sym_conjunction_repeat1] = "conjunction_repeat1",
  [aux_sym_disjunction_repeat1] = "disjunction_repeat1",
  [aux_sym_sequence_repeat1] = "sequence_repeat1",
  [aux_sym_attributes_repeat1] = "attributes_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_COLON_EQ] = anon_sym_COLON_EQ,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_AMP] = anon_sym_AMP,
  [anon_sym_PIPE] = anon_sym_PIPE,
  [anon_sym_BANG] = anon_sym_BANG,
  [anon_sym_QMARK] = anon_sym_QMARK,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [sym_regex] = sym_regex,
  [anon_sym_EQ] = anon_sym_EQ,
  [sym_relation_operator] = sym_relation_operator,
  [anon_sym_TILDE] = anon_sym_TILDE,
  [anon_sym_AT] = anon_sym_AT,
  [sym_identifier] = sym_identifier,
  [sym_source_file] = sym_source_file,
  [sym_pattern_definition] = sym_pattern_definition,
  [sym_pattern_name] = sym_pattern_name,
  [sym_query] = sym_query,
  [sym_expression] = sym_expression,
  [sym_conjunction] = sym_conjunction,
  [sym_disjunction] = sym_disjunction,
  [sym_sequence] = sym_sequence,
  [sym_term] = sym_term,
  [sym_postfix_term] = sym_postfix_term,
  [sym_primary_term] = sym_primary_term,
  [sym_node_pattern] = sym_node_pattern,
  [sym_attributes] = sym_attributes,
  [sym_attribute] = sym_attribute,
  [sym_key] = sym_key,
  [sym_value] = sym_value,
  [sym_node_name] = sym_node_name,
  [sym_name] = sym_name,
  [sym_relation_pattern] = sym_relation_pattern,
  [sym_relation_label] = sym_relation_label,
  [sym_edge_name] = sym_edge_name,
  [sym_pattern_reference] = sym_pattern_reference,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_query_repeat1] = aux_sym_query_repeat1,
  [aux_sym_conjunction_repeat1] = aux_sym_conjunction_repeat1,
  [aux_sym_disjunction_repeat1] = aux_sym_disjunction_repeat1,
  [aux_sym_sequence_repeat1] = aux_sym_sequence_repeat1,
  [aux_sym_attributes_repeat1] = aux_sym_attributes_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_COLON_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AMP] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PIPE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_QMARK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [sym_regex] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [sym_relation_operator] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_TILDE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AT] = {
    .visible = true,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_pattern_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_pattern_name] = {
    .visible = true,
    .named = true,
  },
  [sym_query] = {
    .visible = true,
    .named = true,
  },
  [sym_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_conjunction] = {
    .visible = true,
    .named = true,
  },
  [sym_disjunction] = {
    .visible = true,
    .named = true,
  },
  [sym_sequence] = {
    .visible = true,
    .named = true,
  },
  [sym_term] = {
    .visible = true,
    .named = true,
  },
  [sym_postfix_term] = {
    .visible = true,
    .named = true,
  },
  [sym_primary_term] = {
    .visible = true,
    .named = true,
  },
  [sym_node_pattern] = {
    .visible = true,
    .named = true,
  },
  [sym_attributes] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute] = {
    .visible = true,
    .named = true,
  },
  [sym_key] = {
    .visible = true,
    .named = true,
  },
  [sym_value] = {
    .visible = true,
    .named = true,
  },
  [sym_node_name] = {
    .visible = true,
    .named = true,
  },
  [sym_name] = {
    .visible = true,
    .named = true,
  },
  [sym_relation_pattern] = {
    .visible = true,
    .named = true,
  },
  [sym_relation_label] = {
    .visible = true,
    .named = true,
  },
  [sym_edge_name] = {
    .visible = true,
    .named = true,
  },
  [sym_pattern_reference] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_query_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_conjunction_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_disjunction_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_sequence_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_attributes_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 6,
  [11] = 4,
  [12] = 5,
  [13] = 7,
  [14] = 14,
  [15] = 14,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 16,
  [20] = 17,
  [21] = 18,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 23,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 28,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 27,
  [44] = 36,
  [45] = 45,
  [46] = 46,
  [47] = 24,
  [48] = 29,
  [49] = 30,
  [50] = 50,
  [51] = 31,
  [52] = 38,
  [53] = 53,
  [54] = 35,
  [55] = 55,
  [56] = 56,
  [57] = 50,
  [58] = 58,
  [59] = 46,
  [60] = 45,
  [61] = 42,
  [62] = 62,
  [63] = 63,
  [64] = 56,
  [65] = 63,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 73,
  [75] = 26,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 33,
  [80] = 80,
  [81] = 25,
  [82] = 82,
  [83] = 41,
  [84] = 40,
  [85] = 39,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 91,
  [95] = 95,
  [96] = 96,
  [97] = 97,
  [98] = 98,
  [99] = 99,
  [100] = 93,
  [101] = 101,
  [102] = 102,
  [103] = 103,
  [104] = 101,
  [105] = 105,
  [106] = 106,
  [107] = 107,
  [108] = 108,
  [109] = 105,
  [110] = 110,
  [111] = 103,
};

static TSCharacterRange sym_identifier_character_set_1[] = {
  {0, 0x08}, {0x0e, 0x1f}, {'"', '#'}, {'%', '%'}, {'\'', '\''}, {'*', '-'}, {'0', '9'}, {'?', '?'},
  {'A', 'Z'}, {'\\', '\\'}, {'^', 'z'}, {0x7f, 0x10ffff},
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(9);
      ADVANCE_MAP(
        '!', 14,
        '$', 3,
        '&', 12,
        '(', 17,
        ')', 18,
        '-', 31,
        '.', 33,
        '/', 4,
        ':', 11,
        ';', 23,
        '<', 28,
        '=', 26,
        '>', 29,
        '?', 16,
        '@', 36,
        '[', 19,
        ']', 20,
        '{', 21,
        '|', 13,
        '}', 22,
        '~', 35,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (lookahead != 0) ADVANCE(37);
      END_STATE();
    case 1:
      ADVANCE_MAP(
        '!', 14,
        '$', 3,
        '&', 12,
        '(', 17,
        ')', 18,
        '-', 32,
        '.', 33,
        ':', 6,
        '<', 28,
        '=', 26,
        '>', 29,
        '?', 15,
        '@', 36,
        '[', 19,
        ']', 20,
        '{', 21,
        '|', 13,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      END_STATE();
    case 2:
      ADVANCE_MAP(
        '!', 14,
        '(', 17,
        '/', 4,
        '=', 25,
        '@', 36,
        '[', 19,
        '{', 21,
        '}', 22,
        '~', 35,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(2);
      if ((!eof && set_contains(sym_identifier_character_set_1, 12, lookahead))) ADVANCE(37);
      END_STATE();
    case 3:
      if (lookahead == '+') ADVANCE(30);
      if (lookahead == '-') ADVANCE(32);
      END_STATE();
    case 4:
      if (lookahead == '/') ADVANCE(24);
      if (lookahead == '\\') ADVANCE(7);
      if (lookahead != 0) ADVANCE(4);
      END_STATE();
    case 5:
      if (lookahead == '=') ADVANCE(27);
      END_STATE();
    case 6:
      if (lookahead == '=') ADVANCE(10);
      END_STATE();
    case 7:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(4);
      END_STATE();
    case 8:
      if (eof) ADVANCE(9);
      ADVANCE_MAP(
        '!', 14,
        '$', 3,
        '&', 12,
        '(', 17,
        ')', 18,
        '-', 31,
        '.', 33,
        ':', 11,
        '<', 28,
        '=', 5,
        '>', 29,
        '@', 36,
        '[', 19,
        ']', 20,
        '{', 21,
        '|', 13,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(8);
      if (lookahead != 0 &&
          (lookahead < '-' || '/' < lookahead) &&
          (lookahead < ':' || '>' < lookahead) &&
          (lookahead < '{' || '~' < lookahead)) ADVANCE(37);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_COLON_EQ);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_AMP);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_PIPE);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_BANG);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_QMARK);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_QMARK);
      if ((!eof && set_contains(sym_identifier_character_set_1, 12, lookahead))) ADVANCE(37);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym_regex);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_EQ);
      if (lookahead == '=') ADVANCE(27);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_relation_operator);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_relation_operator);
      if (lookahead == '+') ADVANCE(30);
      if (lookahead == '-') ADVANCE(32);
      if (lookahead == '<') ADVANCE(27);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_relation_operator);
      if (lookahead == '+') ADVANCE(30);
      if (lookahead == '-') ADVANCE(32);
      if (lookahead == '>') ADVANCE(27);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_relation_operator);
      if (lookahead == '+') ADVANCE(27);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_relation_operator);
      if (lookahead == '-') ADVANCE(34);
      if ((!eof && set_contains(sym_identifier_character_set_1, 12, lookahead))) ADVANCE(37);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_relation_operator);
      if (lookahead == '-') ADVANCE(27);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_relation_operator);
      if (lookahead == '.') ADVANCE(27);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_relation_operator);
      if ((!eof && set_contains(sym_identifier_character_set_1, 12, lookahead))) ADVANCE(37);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_TILDE);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_AT);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_identifier);
      if ((!eof && set_contains(sym_identifier_character_set_1, 12, lookahead))) ADVANCE(37);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 8},
  [2] = {.lex_state = 8},
  [3] = {.lex_state = 8},
  [4] = {.lex_state = 8},
  [5] = {.lex_state = 8},
  [6] = {.lex_state = 1},
  [7] = {.lex_state = 1},
  [8] = {.lex_state = 1},
  [9] = {.lex_state = 1},
  [10] = {.lex_state = 1},
  [11] = {.lex_state = 1},
  [12] = {.lex_state = 1},
  [13] = {.lex_state = 1},
  [14] = {.lex_state = 1},
  [15] = {.lex_state = 1},
  [16] = {.lex_state = 1},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 1},
  [20] = {.lex_state = 1},
  [21] = {.lex_state = 1},
  [22] = {.lex_state = 8},
  [23] = {.lex_state = 1},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 8},
  [26] = {.lex_state = 8},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 8},
  [34] = {.lex_state = 8},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 1},
  [38] = {.lex_state = 1},
  [39] = {.lex_state = 8},
  [40] = {.lex_state = 8},
  [41] = {.lex_state = 8},
  [42] = {.lex_state = 8},
  [43] = {.lex_state = 1},
  [44] = {.lex_state = 1},
  [45] = {.lex_state = 8},
  [46] = {.lex_state = 8},
  [47] = {.lex_state = 1},
  [48] = {.lex_state = 1},
  [49] = {.lex_state = 1},
  [50] = {.lex_state = 8},
  [51] = {.lex_state = 1},
  [52] = {.lex_state = 1},
  [53] = {.lex_state = 8},
  [54] = {.lex_state = 1},
  [55] = {.lex_state = 2},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 1},
  [58] = {.lex_state = 2},
  [59] = {.lex_state = 1},
  [60] = {.lex_state = 1},
  [61] = {.lex_state = 1},
  [62] = {.lex_state = 8},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 8},
  [67] = {.lex_state = 8},
  [68] = {.lex_state = 8},
  [69] = {.lex_state = 8},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 2},
  [74] = {.lex_state = 2},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 2},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 2},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 2},
  [91] = {.lex_state = 2},
  [92] = {.lex_state = 0},
  [93] = {.lex_state = 2},
  [94] = {.lex_state = 2},
  [95] = {.lex_state = 2},
  [96] = {.lex_state = 2},
  [97] = {.lex_state = 0},
  [98] = {.lex_state = 0},
  [99] = {.lex_state = 0},
  [100] = {.lex_state = 2},
  [101] = {.lex_state = 0},
  [102] = {.lex_state = 0},
  [103] = {.lex_state = 0},
  [104] = {.lex_state = 0},
  [105] = {.lex_state = 0},
  [106] = {.lex_state = 0},
  [107] = {.lex_state = 0},
  [108] = {.lex_state = 1},
  [109] = {.lex_state = 0},
  [110] = {.lex_state = 0},
  [111] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_AMP] = ACTIONS(1),
    [anon_sym_PIPE] = ACTIONS(1),
    [anon_sym_BANG] = ACTIONS(1),
    [anon_sym_QMARK] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [sym_regex] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [sym_relation_operator] = ACTIONS(1),
    [anon_sym_TILDE] = ACTIONS(1),
    [anon_sym_AT] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(110),
    [sym_pattern_definition] = STATE(2),
    [sym_pattern_name] = STATE(108),
    [sym_query] = STATE(2),
    [sym_expression] = STATE(62),
    [sym_conjunction] = STATE(53),
    [sym_disjunction] = STATE(39),
    [sym_sequence] = STATE(26),
    [sym_term] = STATE(4),
    [sym_postfix_term] = STATE(50),
    [sym_primary_term] = STATE(27),
    [sym_node_pattern] = STATE(36),
    [sym_relation_pattern] = STATE(65),
    [sym_pattern_reference] = STATE(36),
    [aux_sym_source_file_repeat1] = STATE(2),
    [aux_sym_sequence_repeat1] = STATE(4),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_BANG] = ACTIONS(5),
    [anon_sym_LPAREN] = ACTIONS(7),
    [anon_sym_LBRACK] = ACTIONS(9),
    [anon_sym_LBRACE] = ACTIONS(11),
    [sym_relation_operator] = ACTIONS(13),
    [anon_sym_AT] = ACTIONS(15),
    [sym_identifier] = ACTIONS(17),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 19,
    ACTIONS(5), 1,
      anon_sym_BANG,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(9), 1,
      anon_sym_LBRACK,
    ACTIONS(11), 1,
      anon_sym_LBRACE,
    ACTIONS(13), 1,
      sym_relation_operator,
    ACTIONS(15), 1,
      anon_sym_AT,
    ACTIONS(17), 1,
      sym_identifier,
    ACTIONS(19), 1,
      ts_builtin_sym_end,
    STATE(26), 1,
      sym_sequence,
    STATE(27), 1,
      sym_primary_term,
    STATE(39), 1,
      sym_disjunction,
    STATE(50), 1,
      sym_postfix_term,
    STATE(53), 1,
      sym_conjunction,
    STATE(62), 1,
      sym_expression,
    STATE(65), 1,
      sym_relation_pattern,
    STATE(108), 1,
      sym_pattern_name,
    STATE(4), 2,
      sym_term,
      aux_sym_sequence_repeat1,
    STATE(36), 2,
      sym_node_pattern,
      sym_pattern_reference,
    STATE(3), 3,
      sym_pattern_definition,
      sym_query,
      aux_sym_source_file_repeat1,
  [62] = 19,
    ACTIONS(21), 1,
      ts_builtin_sym_end,
    ACTIONS(23), 1,
      anon_sym_BANG,
    ACTIONS(26), 1,
      anon_sym_LPAREN,
    ACTIONS(29), 1,
      anon_sym_LBRACK,
    ACTIONS(32), 1,
      anon_sym_LBRACE,
    ACTIONS(35), 1,
      sym_relation_operator,
    ACTIONS(38), 1,
      anon_sym_AT,
    ACTIONS(41), 1,
      sym_identifier,
    STATE(26), 1,
      sym_sequence,
    STATE(27), 1,
      sym_primary_term,
    STATE(39), 1,
      sym_disjunction,
    STATE(50), 1,
      sym_postfix_term,
    STATE(53), 1,
      sym_conjunction,
    STATE(62), 1,
      sym_expression,
    STATE(65), 1,
      sym_relation_pattern,
    STATE(108), 1,
      sym_pattern_name,
    STATE(4), 2,
      sym_term,
      aux_sym_sequence_repeat1,
    STATE(36), 2,
      sym_node_pattern,
      sym_pattern_reference,
    STATE(3), 3,
      sym_pattern_definition,
      sym_query,
      aux_sym_source_file_repeat1,
  [124] = 7,
    STATE(27), 1,
      sym_primary_term,
    STATE(50), 1,
      sym_postfix_term,
    STATE(65), 1,
      sym_relation_pattern,
    ACTIONS(46), 2,
      sym_relation_operator,
      sym_identifier,
    STATE(5), 2,
      sym_term,
      aux_sym_sequence_repeat1,
    STATE(36), 2,
      sym_node_pattern,
      sym_pattern_reference,
    ACTIONS(44), 9,
      ts_builtin_sym_end,
      anon_sym_COLON,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_BANG,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      anon_sym_AT,
  [157] = 13,
    ACTIONS(50), 1,
      anon_sym_BANG,
    ACTIONS(53), 1,
      anon_sym_LPAREN,
    ACTIONS(56), 1,
      anon_sym_LBRACK,
    ACTIONS(59), 1,
      anon_sym_LBRACE,
    ACTIONS(62), 1,
      sym_relation_operator,
    ACTIONS(65), 1,
      anon_sym_AT,
    ACTIONS(68), 1,
      sym_identifier,
    STATE(27), 1,
      sym_primary_term,
    STATE(50), 1,
      sym_postfix_term,
    STATE(65), 1,
      sym_relation_pattern,
    STATE(5), 2,
      sym_term,
      aux_sym_sequence_repeat1,
    STATE(36), 2,
      sym_node_pattern,
      sym_pattern_reference,
    ACTIONS(48), 4,
      ts_builtin_sym_end,
      anon_sym_COLON,
      anon_sym_AMP,
      anon_sym_PIPE,
  [202] = 15,
    ACTIONS(70), 1,
      anon_sym_BANG,
    ACTIONS(72), 1,
      anon_sym_LPAREN,
    ACTIONS(74), 1,
      anon_sym_LBRACK,
    ACTIONS(76), 1,
      anon_sym_LBRACE,
    ACTIONS(78), 1,
      sym_relation_operator,
    ACTIONS(80), 1,
      anon_sym_AT,
    STATE(43), 1,
      sym_primary_term,
    STATE(53), 1,
      sym_conjunction,
    STATE(57), 1,
      sym_postfix_term,
    STATE(63), 1,
      sym_relation_pattern,
    STATE(75), 1,
      sym_sequence,
    STATE(85), 1,
      sym_disjunction,
    STATE(104), 1,
      sym_expression,
    STATE(11), 2,
      sym_term,
      aux_sym_sequence_repeat1,
    STATE(44), 2,
      sym_node_pattern,
      sym_pattern_reference,
  [250] = 15,
    ACTIONS(70), 1,
      anon_sym_BANG,
    ACTIONS(72), 1,
      anon_sym_LPAREN,
    ACTIONS(74), 1,
      anon_sym_LBRACK,
    ACTIONS(76), 1,
      anon_sym_LBRACE,
    ACTIONS(78), 1,
      sym_relation_operator,
    ACTIONS(80), 1,
      anon_sym_AT,
    STATE(43), 1,
      sym_primary_term,
    STATE(53), 1,
      sym_conjunction,
    STATE(57), 1,
      sym_postfix_term,
    STATE(63), 1,
      sym_relation_pattern,
    STATE(75), 1,
      sym_sequence,
    STATE(85), 1,
      sym_disjunction,
    STATE(111), 1,
      sym_expression,
    STATE(11), 2,
      sym_term,
      aux_sym_sequence_repeat1,
    STATE(44), 2,
      sym_node_pattern,
      sym_pattern_reference,
  [298] = 15,
    ACTIONS(5), 1,
      anon_sym_BANG,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(9), 1,
      anon_sym_LBRACK,
    ACTIONS(11), 1,
      anon_sym_LBRACE,
    ACTIONS(15), 1,
      anon_sym_AT,
    ACTIONS(78), 1,
      sym_relation_operator,
    STATE(26), 1,
      sym_sequence,
    STATE(27), 1,
      sym_primary_term,
    STATE(39), 1,
      sym_disjunction,
    STATE(50), 1,
      sym_postfix_term,
    STATE(53), 1,
      sym_conjunction,
    STATE(65), 1,
      sym_relation_pattern,
    STATE(68), 1,
      sym_expression,
    STATE(4), 2,
      sym_term,
      aux_sym_sequence_repeat1,
    STATE(36), 2,
      sym_node_pattern,
      sym_pattern_reference,
  [346] = 15,
    ACTIONS(5), 1,
      anon_sym_BANG,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(9), 1,
      anon_sym_LBRACK,
    ACTIONS(11), 1,
      anon_sym_LBRACE,
    ACTIONS(15), 1,
      anon_sym_AT,
    ACTIONS(78), 1,
      sym_relation_operator,
    STATE(26), 1,
      sym_sequence,
    STATE(27), 1,
      sym_primary_term,
    STATE(39), 1,
      sym_disjunction,
    STATE(50), 1,
      sym_postfix_term,
    STATE(53), 1,
      sym_conjunction,
    STATE(65), 1,
      sym_relation_pattern,
    STATE(69), 1,
      sym_expression,
    STATE(4), 2,
      sym_term,
      aux_sym_sequence_repeat1,
    STATE(36), 2,
      sym_node_pattern,
      sym_pattern_reference,
  [394] = 15,
    ACTIONS(70), 1,
      anon_sym_BANG,
    ACTIONS(72), 1,
      anon_sym_LPAREN,
    ACTIONS(74), 1,
      anon_sym_LBRACK,
    ACTIONS(76), 1,
      anon_sym_LBRACE,
    ACTIONS(78), 1,
      sym_relation_operator,
    ACTIONS(80), 1,
      anon_sym_AT,
    STATE(43), 1,
      sym_primary_term,
    STATE(53), 1,
      sym_conjunction,
    STATE(57), 1,
      sym_postfix_term,
    STATE(63), 1,
      sym_relation_pattern,
    STATE(75), 1,
      sym_sequence,
    STATE(85), 1,
      sym_disjunction,
    STATE(101), 1,
      sym_expression,
    STATE(11), 2,
      sym_term,
      aux_sym_sequence_repeat1,
    STATE(44), 2,
      sym_node_pattern,
      sym_pattern_reference,
  [442] = 12,
    ACTIONS(70), 1,
      anon_sym_BANG,
    ACTIONS(72), 1,
      anon_sym_LPAREN,
    ACTIONS(74), 1,
      anon_sym_LBRACK,
    ACTIONS(76), 1,
      anon_sym_LBRACE,
    ACTIONS(78), 1,
      sym_relation_operator,
    ACTIONS(80), 1,
      anon_sym_AT,
    STATE(43), 1,
      sym_primary_term,
    STATE(57), 1,
      sym_postfix_term,
    STATE(63), 1,
      sym_relation_pattern,
    STATE(12), 2,
      sym_term,
      aux_sym_sequence_repeat1,
    STATE(44), 2,
      sym_node_pattern,
      sym_pattern_reference,
    ACTIONS(44), 4,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [484] = 12,
    ACTIONS(82), 1,
      anon_sym_BANG,
    ACTIONS(85), 1,
      anon_sym_LPAREN,
    ACTIONS(88), 1,
      anon_sym_LBRACK,
    ACTIONS(91), 1,
      anon_sym_LBRACE,
    ACTIONS(94), 1,
      sym_relation_operator,
    ACTIONS(97), 1,
      anon_sym_AT,
    STATE(43), 1,
      sym_primary_term,
    STATE(57), 1,
      sym_postfix_term,
    STATE(63), 1,
      sym_relation_pattern,
    STATE(12), 2,
      sym_term,
      aux_sym_sequence_repeat1,
    STATE(44), 2,
      sym_node_pattern,
      sym_pattern_reference,
    ACTIONS(48), 4,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [526] = 15,
    ACTIONS(70), 1,
      anon_sym_BANG,
    ACTIONS(72), 1,
      anon_sym_LPAREN,
    ACTIONS(74), 1,
      anon_sym_LBRACK,
    ACTIONS(76), 1,
      anon_sym_LBRACE,
    ACTIONS(78), 1,
      sym_relation_operator,
    ACTIONS(80), 1,
      anon_sym_AT,
    STATE(43), 1,
      sym_primary_term,
    STATE(53), 1,
      sym_conjunction,
    STATE(57), 1,
      sym_postfix_term,
    STATE(63), 1,
      sym_relation_pattern,
    STATE(75), 1,
      sym_sequence,
    STATE(85), 1,
      sym_disjunction,
    STATE(103), 1,
      sym_expression,
    STATE(11), 2,
      sym_term,
      aux_sym_sequence_repeat1,
    STATE(44), 2,
      sym_node_pattern,
      sym_pattern_reference,
  [574] = 13,
    ACTIONS(5), 1,
      anon_sym_BANG,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(9), 1,
      anon_sym_LBRACK,
    ACTIONS(11), 1,
      anon_sym_LBRACE,
    ACTIONS(15), 1,
      anon_sym_AT,
    ACTIONS(78), 1,
      sym_relation_operator,
    STATE(26), 1,
      sym_sequence,
    STATE(27), 1,
      sym_primary_term,
    STATE(34), 1,
      sym_disjunction,
    STATE(50), 1,
      sym_postfix_term,
    STATE(65), 1,
      sym_relation_pattern,
    STATE(4), 2,
      sym_term,
      aux_sym_sequence_repeat1,
    STATE(36), 2,
      sym_node_pattern,
      sym_pattern_reference,
  [616] = 13,
    ACTIONS(70), 1,
      anon_sym_BANG,
    ACTIONS(72), 1,
      anon_sym_LPAREN,
    ACTIONS(74), 1,
      anon_sym_LBRACK,
    ACTIONS(76), 1,
      anon_sym_LBRACE,
    ACTIONS(78), 1,
      sym_relation_operator,
    ACTIONS(80), 1,
      anon_sym_AT,
    STATE(34), 1,
      sym_disjunction,
    STATE(43), 1,
      sym_primary_term,
    STATE(57), 1,
      sym_postfix_term,
    STATE(63), 1,
      sym_relation_pattern,
    STATE(75), 1,
      sym_sequence,
    STATE(11), 2,
      sym_term,
      aux_sym_sequence_repeat1,
    STATE(44), 2,
      sym_node_pattern,
      sym_pattern_reference,
  [658] = 12,
    ACTIONS(5), 1,
      anon_sym_BANG,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(9), 1,
      anon_sym_LBRACK,
    ACTIONS(11), 1,
      anon_sym_LBRACE,
    ACTIONS(15), 1,
      anon_sym_AT,
    ACTIONS(78), 1,
      sym_relation_operator,
    STATE(22), 1,
      sym_sequence,
    STATE(27), 1,
      sym_primary_term,
    STATE(50), 1,
      sym_postfix_term,
    STATE(65), 1,
      sym_relation_pattern,
    STATE(4), 2,
      sym_term,
      aux_sym_sequence_repeat1,
    STATE(36), 2,
      sym_node_pattern,
      sym_pattern_reference,
  [697] = 4,
    ACTIONS(104), 1,
      anon_sym_EQ,
    STATE(29), 1,
      sym_node_name,
    ACTIONS(102), 3,
      anon_sym_QMARK,
      sym_relation_operator,
      sym_identifier,
    ACTIONS(100), 9,
      ts_builtin_sym_end,
      anon_sym_COLON,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_BANG,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      anon_sym_AT,
  [720] = 4,
    ACTIONS(104), 1,
      anon_sym_EQ,
    STATE(35), 1,
      sym_node_name,
    ACTIONS(108), 3,
      anon_sym_QMARK,
      sym_relation_operator,
      sym_identifier,
    ACTIONS(106), 9,
      ts_builtin_sym_end,
      anon_sym_COLON,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_BANG,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      anon_sym_AT,
  [743] = 12,
    ACTIONS(70), 1,
      anon_sym_BANG,
    ACTIONS(72), 1,
      anon_sym_LPAREN,
    ACTIONS(74), 1,
      anon_sym_LBRACK,
    ACTIONS(76), 1,
      anon_sym_LBRACE,
    ACTIONS(78), 1,
      sym_relation_operator,
    ACTIONS(80), 1,
      anon_sym_AT,
    STATE(22), 1,
      sym_sequence,
    STATE(43), 1,
      sym_primary_term,
    STATE(57), 1,
      sym_postfix_term,
    STATE(63), 1,
      sym_relation_pattern,
    STATE(11), 2,
      sym_term,
      aux_sym_sequence_repeat1,
    STATE(44), 2,
      sym_node_pattern,
      sym_pattern_reference,
  [782] = 3,
    ACTIONS(110), 1,
      anon_sym_EQ,
    STATE(48), 1,
      sym_node_name,
    ACTIONS(100), 11,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_BANG,
      anon_sym_QMARK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      sym_relation_operator,
      anon_sym_AT,
  [802] = 3,
    ACTIONS(110), 1,
      anon_sym_EQ,
    STATE(54), 1,
      sym_node_name,
    ACTIONS(106), 11,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_BANG,
      anon_sym_QMARK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      sym_relation_operator,
      anon_sym_AT,
  [822] = 2,
    ACTIONS(114), 2,
      sym_relation_operator,
      sym_identifier,
    ACTIONS(112), 11,
      ts_builtin_sym_end,
      anon_sym_COLON,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_BANG,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_AT,
  [840] = 1,
    ACTIONS(116), 12,
      anon_sym_COLON_EQ,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_BANG,
      anon_sym_QMARK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      sym_relation_operator,
      anon_sym_AT,
  [855] = 2,
    ACTIONS(120), 3,
      anon_sym_QMARK,
      sym_relation_operator,
      sym_identifier,
    ACTIONS(118), 9,
      ts_builtin_sym_end,
      anon_sym_COLON,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_BANG,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      anon_sym_AT,
  [872] = 4,
    ACTIONS(124), 1,
      anon_sym_PIPE,
    STATE(33), 1,
      aux_sym_disjunction_repeat1,
    ACTIONS(126), 2,
      sym_relation_operator,
      sym_identifier,
    ACTIONS(122), 8,
      ts_builtin_sym_end,
      anon_sym_COLON,
      anon_sym_AMP,
      anon_sym_BANG,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      anon_sym_AT,
  [893] = 4,
    ACTIONS(124), 1,
      anon_sym_PIPE,
    STATE(25), 1,
      aux_sym_disjunction_repeat1,
    ACTIONS(130), 2,
      sym_relation_operator,
      sym_identifier,
    ACTIONS(128), 8,
      ts_builtin_sym_end,
      anon_sym_COLON,
      anon_sym_AMP,
      anon_sym_BANG,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      anon_sym_AT,
  [914] = 3,
    ACTIONS(134), 1,
      anon_sym_QMARK,
    ACTIONS(136), 2,
      sym_relation_operator,
      sym_identifier,
    ACTIONS(132), 9,
      ts_builtin_sym_end,
      anon_sym_COLON,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_BANG,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      anon_sym_AT,
  [933] = 2,
    ACTIONS(140), 3,
      anon_sym_QMARK,
      sym_relation_operator,
      sym_identifier,
    ACTIONS(138), 9,
      ts_builtin_sym_end,
      anon_sym_COLON,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_BANG,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      anon_sym_AT,
  [950] = 2,
    ACTIONS(108), 3,
      anon_sym_QMARK,
      sym_relation_operator,
      sym_identifier,
    ACTIONS(106), 9,
      ts_builtin_sym_end,
      anon_sym_COLON,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_BANG,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      anon_sym_AT,
  [967] = 2,
    ACTIONS(144), 3,
      anon_sym_QMARK,
      sym_relation_operator,
      sym_identifier,
    ACTIONS(142), 9,
      ts_builtin_sym_end,
      anon_sym_COLON,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_BANG,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      anon_sym_AT,
  [984] = 2,
    ACTIONS(148), 3,
      anon_sym_QMARK,
      sym_relation_operator,
      sym_identifier,
    ACTIONS(146), 9,
      ts_builtin_sym_end,
      anon_sym_COLON,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_BANG,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      anon_sym_AT,
  [1001] = 2,
    ACTIONS(150), 3,
      anon_sym_QMARK,
      sym_relation_operator,
      sym_identifier,
    ACTIONS(116), 9,
      ts_builtin_sym_end,
      anon_sym_COLON,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_BANG,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      anon_sym_AT,
  [1018] = 4,
    ACTIONS(152), 1,
      anon_sym_PIPE,
    STATE(33), 1,
      aux_sym_disjunction_repeat1,
    ACTIONS(114), 2,
      sym_relation_operator,
      sym_identifier,
    ACTIONS(112), 8,
      ts_builtin_sym_end,
      anon_sym_COLON,
      anon_sym_AMP,
      anon_sym_BANG,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      anon_sym_AT,
  [1039] = 2,
    ACTIONS(157), 2,
      sym_relation_operator,
      sym_identifier,
    ACTIONS(155), 10,
      ts_builtin_sym_end,
      anon_sym_COLON,
      anon_sym_AMP,
      anon_sym_BANG,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_AT,
  [1056] = 2,
    ACTIONS(161), 3,
      anon_sym_QMARK,
      sym_relation_operator,
      sym_identifier,
    ACTIONS(159), 9,
      ts_builtin_sym_end,
      anon_sym_COLON,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_BANG,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      anon_sym_AT,
  [1073] = 2,
    ACTIONS(165), 3,
      anon_sym_QMARK,
      sym_relation_operator,
      sym_identifier,
    ACTIONS(163), 9,
      ts_builtin_sym_end,
      anon_sym_COLON,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_BANG,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      anon_sym_AT,
  [1090] = 1,
    ACTIONS(138), 11,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_BANG,
      anon_sym_QMARK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      sym_relation_operator,
      anon_sym_AT,
  [1104] = 10,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(9), 1,
      anon_sym_LBRACK,
    ACTIONS(11), 1,
      anon_sym_LBRACE,
    ACTIONS(15), 1,
      anon_sym_AT,
    ACTIONS(167), 1,
      anon_sym_BANG,
    ACTIONS(169), 1,
      sym_relation_operator,
    STATE(27), 1,
      sym_primary_term,
    STATE(46), 1,
      sym_term,
    STATE(50), 1,
      sym_postfix_term,
    STATE(36), 2,
      sym_node_pattern,
      sym_pattern_reference,
  [1136] = 4,
    ACTIONS(173), 1,
      anon_sym_AMP,
    STATE(41), 1,
      aux_sym_conjunction_repeat1,
    ACTIONS(175), 2,
      sym_relation_operator,
      sym_identifier,
    ACTIONS(171), 7,
      ts_builtin_sym_end,
      anon_sym_COLON,
      anon_sym_BANG,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      anon_sym_AT,
  [1156] = 4,
    ACTIONS(177), 1,
      anon_sym_AMP,
    STATE(40), 1,
      aux_sym_conjunction_repeat1,
    ACTIONS(157), 2,
      sym_relation_operator,
      sym_identifier,
    ACTIONS(155), 7,
      ts_builtin_sym_end,
      anon_sym_COLON,
      anon_sym_BANG,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      anon_sym_AT,
  [1176] = 4,
    ACTIONS(173), 1,
      anon_sym_AMP,
    STATE(40), 1,
      aux_sym_conjunction_repeat1,
    ACTIONS(182), 2,
      sym_relation_operator,
      sym_identifier,
    ACTIONS(180), 7,
      ts_builtin_sym_end,
      anon_sym_COLON,
      anon_sym_BANG,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      anon_sym_AT,
  [1196] = 2,
    ACTIONS(186), 2,
      sym_relation_operator,
      sym_identifier,
    ACTIONS(184), 9,
      ts_builtin_sym_end,
      anon_sym_COLON,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_BANG,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      anon_sym_AT,
  [1212] = 2,
    ACTIONS(188), 1,
      anon_sym_QMARK,
    ACTIONS(132), 10,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_BANG,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      sym_relation_operator,
      anon_sym_AT,
  [1228] = 1,
    ACTIONS(163), 11,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_BANG,
      anon_sym_QMARK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      sym_relation_operator,
      anon_sym_AT,
  [1242] = 2,
    ACTIONS(68), 2,
      sym_relation_operator,
      sym_identifier,
    ACTIONS(48), 9,
      ts_builtin_sym_end,
      anon_sym_COLON,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_BANG,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      anon_sym_AT,
  [1258] = 2,
    ACTIONS(192), 2,
      sym_relation_operator,
      sym_identifier,
    ACTIONS(190), 9,
      ts_builtin_sym_end,
      anon_sym_COLON,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_BANG,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      anon_sym_AT,
  [1274] = 1,
    ACTIONS(118), 11,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_BANG,
      anon_sym_QMARK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      sym_relation_operator,
      anon_sym_AT,
  [1288] = 1,
    ACTIONS(106), 11,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_BANG,
      anon_sym_QMARK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      sym_relation_operator,
      anon_sym_AT,
  [1302] = 1,
    ACTIONS(142), 11,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_BANG,
      anon_sym_QMARK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      sym_relation_operator,
      anon_sym_AT,
  [1316] = 2,
    ACTIONS(196), 2,
      sym_relation_operator,
      sym_identifier,
    ACTIONS(194), 9,
      ts_builtin_sym_end,
      anon_sym_COLON,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_BANG,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      anon_sym_AT,
  [1332] = 1,
    ACTIONS(146), 11,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_BANG,
      anon_sym_QMARK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      sym_relation_operator,
      anon_sym_AT,
  [1346] = 10,
    ACTIONS(72), 1,
      anon_sym_LPAREN,
    ACTIONS(74), 1,
      anon_sym_LBRACK,
    ACTIONS(76), 1,
      anon_sym_LBRACE,
    ACTIONS(80), 1,
      anon_sym_AT,
    ACTIONS(169), 1,
      sym_relation_operator,
    ACTIONS(198), 1,
      anon_sym_BANG,
    STATE(43), 1,
      sym_primary_term,
    STATE(57), 1,
      sym_postfix_term,
    STATE(59), 1,
      sym_term,
    STATE(44), 2,
      sym_node_pattern,
      sym_pattern_reference,
  [1378] = 2,
    ACTIONS(202), 2,
      sym_relation_operator,
      sym_identifier,
    ACTIONS(200), 9,
      ts_builtin_sym_end,
      anon_sym_COLON,
      anon_sym_BANG,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_AT,
  [1394] = 1,
    ACTIONS(159), 11,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_BANG,
      anon_sym_QMARK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      sym_relation_operator,
      anon_sym_AT,
  [1408] = 5,
    ACTIONS(208), 1,
      sym_identifier,
    STATE(71), 1,
      sym_relation_label,
    STATE(77), 1,
      sym_edge_name,
    ACTIONS(206), 2,
      anon_sym_EQ,
      anon_sym_TILDE,
    ACTIONS(204), 5,
      anon_sym_BANG,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      anon_sym_AT,
  [1429] = 9,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(9), 1,
      anon_sym_LBRACK,
    ACTIONS(11), 1,
      anon_sym_LBRACE,
    ACTIONS(15), 1,
      anon_sym_AT,
    ACTIONS(167), 1,
      anon_sym_BANG,
    STATE(27), 1,
      sym_primary_term,
    STATE(46), 1,
      sym_term,
    STATE(50), 1,
      sym_postfix_term,
    STATE(36), 2,
      sym_node_pattern,
      sym_pattern_reference,
  [1458] = 1,
    ACTIONS(194), 10,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_BANG,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      sym_relation_operator,
      anon_sym_AT,
  [1471] = 5,
    ACTIONS(208), 1,
      sym_identifier,
    STATE(70), 1,
      sym_relation_label,
    STATE(76), 1,
      sym_edge_name,
    ACTIONS(206), 2,
      anon_sym_EQ,
      anon_sym_TILDE,
    ACTIONS(210), 5,
      anon_sym_BANG,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      anon_sym_AT,
  [1492] = 1,
    ACTIONS(190), 10,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_BANG,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      sym_relation_operator,
      anon_sym_AT,
  [1505] = 1,
    ACTIONS(48), 10,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_BANG,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      sym_relation_operator,
      anon_sym_AT,
  [1518] = 1,
    ACTIONS(184), 10,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_BANG,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      sym_relation_operator,
      anon_sym_AT,
  [1531] = 4,
    ACTIONS(214), 1,
      anon_sym_COLON,
    STATE(66), 1,
      aux_sym_query_repeat1,
    ACTIONS(216), 2,
      sym_relation_operator,
      sym_identifier,
    ACTIONS(212), 6,
      ts_builtin_sym_end,
      anon_sym_BANG,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      anon_sym_AT,
  [1550] = 9,
    ACTIONS(72), 1,
      anon_sym_LPAREN,
    ACTIONS(74), 1,
      anon_sym_LBRACK,
    ACTIONS(76), 1,
      anon_sym_LBRACE,
    ACTIONS(80), 1,
      anon_sym_AT,
    ACTIONS(198), 1,
      anon_sym_BANG,
    STATE(43), 1,
      sym_primary_term,
    STATE(57), 1,
      sym_postfix_term,
    STATE(60), 1,
      sym_term,
    STATE(44), 2,
      sym_node_pattern,
      sym_pattern_reference,
  [1579] = 9,
    ACTIONS(72), 1,
      anon_sym_LPAREN,
    ACTIONS(74), 1,
      anon_sym_LBRACK,
    ACTIONS(76), 1,
      anon_sym_LBRACE,
    ACTIONS(80), 1,
      anon_sym_AT,
    ACTIONS(198), 1,
      anon_sym_BANG,
    STATE(43), 1,
      sym_primary_term,
    STATE(57), 1,
      sym_postfix_term,
    STATE(59), 1,
      sym_term,
    STATE(44), 2,
      sym_node_pattern,
      sym_pattern_reference,
  [1608] = 9,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(9), 1,
      anon_sym_LBRACK,
    ACTIONS(11), 1,
      anon_sym_LBRACE,
    ACTIONS(15), 1,
      anon_sym_AT,
    ACTIONS(167), 1,
      anon_sym_BANG,
    STATE(27), 1,
      sym_primary_term,
    STATE(45), 1,
      sym_term,
    STATE(50), 1,
      sym_postfix_term,
    STATE(36), 2,
      sym_node_pattern,
      sym_pattern_reference,
  [1637] = 4,
    ACTIONS(214), 1,
      anon_sym_COLON,
    STATE(67), 1,
      aux_sym_query_repeat1,
    ACTIONS(220), 2,
      sym_relation_operator,
      sym_identifier,
    ACTIONS(218), 6,
      ts_builtin_sym_end,
      anon_sym_BANG,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      anon_sym_AT,
  [1656] = 4,
    ACTIONS(224), 1,
      anon_sym_COLON,
    STATE(67), 1,
      aux_sym_query_repeat1,
    ACTIONS(227), 2,
      sym_relation_operator,
      sym_identifier,
    ACTIONS(222), 6,
      ts_builtin_sym_end,
      anon_sym_BANG,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      anon_sym_AT,
  [1675] = 2,
    ACTIONS(227), 2,
      sym_relation_operator,
      sym_identifier,
    ACTIONS(222), 7,
      ts_builtin_sym_end,
      anon_sym_COLON,
      anon_sym_BANG,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      anon_sym_AT,
  [1689] = 2,
    ACTIONS(231), 2,
      sym_relation_operator,
      sym_identifier,
    ACTIONS(229), 6,
      ts_builtin_sym_end,
      anon_sym_BANG,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      anon_sym_AT,
  [1702] = 3,
    STATE(80), 1,
      sym_edge_name,
    ACTIONS(206), 2,
      anon_sym_EQ,
      anon_sym_TILDE,
    ACTIONS(233), 5,
      anon_sym_BANG,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      anon_sym_AT,
  [1717] = 3,
    STATE(76), 1,
      sym_edge_name,
    ACTIONS(206), 2,
      anon_sym_EQ,
      anon_sym_TILDE,
    ACTIONS(210), 5,
      anon_sym_BANG,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      anon_sym_AT,
  [1732] = 1,
    ACTIONS(235), 7,
      anon_sym_BANG,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      anon_sym_EQ,
      anon_sym_TILDE,
      anon_sym_AT,
  [1742] = 6,
    ACTIONS(237), 1,
      anon_sym_BANG,
    ACTIONS(239), 1,
      anon_sym_RBRACE,
    ACTIONS(241), 1,
      sym_identifier,
    STATE(89), 1,
      sym_attribute,
    STATE(102), 1,
      sym_key,
    STATE(109), 1,
      sym_attributes,
  [1761] = 6,
    ACTIONS(237), 1,
      anon_sym_BANG,
    ACTIONS(241), 1,
      sym_identifier,
    ACTIONS(243), 1,
      anon_sym_RBRACE,
    STATE(89), 1,
      sym_attribute,
    STATE(102), 1,
      sym_key,
    STATE(105), 1,
      sym_attributes,
  [1780] = 3,
    ACTIONS(245), 1,
      anon_sym_PIPE,
    STATE(81), 1,
      aux_sym_disjunction_repeat1,
    ACTIONS(128), 3,
      anon_sym_AMP,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [1792] = 1,
    ACTIONS(233), 5,
      anon_sym_BANG,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      anon_sym_AT,
  [1800] = 1,
    ACTIONS(210), 5,
      anon_sym_BANG,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      anon_sym_AT,
  [1808] = 1,
    ACTIONS(247), 5,
      anon_sym_BANG,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      anon_sym_AT,
  [1816] = 3,
    ACTIONS(249), 1,
      anon_sym_PIPE,
    STATE(79), 1,
      aux_sym_disjunction_repeat1,
    ACTIONS(112), 3,
      anon_sym_AMP,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [1828] = 1,
    ACTIONS(252), 5,
      anon_sym_BANG,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      anon_sym_AT,
  [1836] = 3,
    ACTIONS(245), 1,
      anon_sym_PIPE,
    STATE(79), 1,
      aux_sym_disjunction_repeat1,
    ACTIONS(122), 3,
      anon_sym_AMP,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [1848] = 4,
    ACTIONS(237), 1,
      anon_sym_BANG,
    ACTIONS(241), 1,
      sym_identifier,
    STATE(92), 1,
      sym_attribute,
    STATE(102), 1,
      sym_key,
  [1861] = 3,
    ACTIONS(254), 1,
      anon_sym_AMP,
    STATE(84), 1,
      aux_sym_conjunction_repeat1,
    ACTIONS(180), 2,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [1872] = 3,
    ACTIONS(256), 1,
      anon_sym_AMP,
    STATE(84), 1,
      aux_sym_conjunction_repeat1,
    ACTIONS(155), 2,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [1883] = 3,
    ACTIONS(254), 1,
      anon_sym_AMP,
    STATE(83), 1,
      aux_sym_conjunction_repeat1,
    ACTIONS(171), 2,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [1894] = 3,
    ACTIONS(259), 1,
      anon_sym_RBRACE,
    ACTIONS(261), 1,
      anon_sym_SEMI,
    STATE(86), 1,
      aux_sym_attributes_repeat1,
  [1904] = 3,
    ACTIONS(264), 1,
      anon_sym_RBRACE,
    ACTIONS(266), 1,
      anon_sym_SEMI,
    STATE(86), 1,
      aux_sym_attributes_repeat1,
  [1914] = 2,
    STATE(98), 1,
      sym_value,
    ACTIONS(268), 2,
      sym_regex,
      sym_identifier,
  [1922] = 3,
    ACTIONS(266), 1,
      anon_sym_SEMI,
    ACTIONS(270), 1,
      anon_sym_RBRACE,
    STATE(87), 1,
      aux_sym_attributes_repeat1,
  [1932] = 2,
    STATE(99), 1,
      sym_value,
    ACTIONS(268), 2,
      sym_regex,
      sym_identifier,
  [1940] = 2,
    ACTIONS(272), 1,
      sym_identifier,
    STATE(51), 1,
      sym_name,
  [1947] = 1,
    ACTIONS(259), 2,
      anon_sym_RBRACE,
      anon_sym_SEMI,
  [1952] = 2,
    ACTIONS(274), 1,
      sym_identifier,
    STATE(47), 1,
      sym_pattern_name,
  [1959] = 2,
    ACTIONS(276), 1,
      sym_identifier,
    STATE(31), 1,
      sym_name,
  [1966] = 2,
    ACTIONS(241), 1,
      sym_identifier,
    STATE(107), 1,
      sym_key,
  [1973] = 2,
    ACTIONS(276), 1,
      sym_identifier,
    STATE(78), 1,
      sym_name,
  [1980] = 1,
    ACTIONS(278), 2,
      anon_sym_RBRACE,
      anon_sym_SEMI,
  [1985] = 1,
    ACTIONS(280), 2,
      anon_sym_RBRACE,
      anon_sym_SEMI,
  [1990] = 1,
    ACTIONS(282), 2,
      anon_sym_RBRACE,
      anon_sym_SEMI,
  [1995] = 2,
    ACTIONS(284), 1,
      sym_identifier,
    STATE(24), 1,
      sym_pattern_name,
  [2002] = 1,
    ACTIONS(286), 1,
      anon_sym_RBRACK,
  [2006] = 1,
    ACTIONS(288), 1,
      anon_sym_COLON,
  [2010] = 1,
    ACTIONS(290), 1,
      anon_sym_RPAREN,
  [2014] = 1,
    ACTIONS(290), 1,
      anon_sym_RBRACK,
  [2018] = 1,
    ACTIONS(292), 1,
      anon_sym_RBRACE,
  [2022] = 1,
    ACTIONS(294), 1,
      anon_sym_COLON,
  [2026] = 1,
    ACTIONS(296), 1,
      anon_sym_COLON,
  [2030] = 1,
    ACTIONS(298), 1,
      anon_sym_COLON_EQ,
  [2034] = 1,
    ACTIONS(300), 1,
      anon_sym_RBRACE,
  [2038] = 1,
    ACTIONS(302), 1,
      ts_builtin_sym_end,
  [2042] = 1,
    ACTIONS(286), 1,
      anon_sym_RPAREN,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 62,
  [SMALL_STATE(4)] = 124,
  [SMALL_STATE(5)] = 157,
  [SMALL_STATE(6)] = 202,
  [SMALL_STATE(7)] = 250,
  [SMALL_STATE(8)] = 298,
  [SMALL_STATE(9)] = 346,
  [SMALL_STATE(10)] = 394,
  [SMALL_STATE(11)] = 442,
  [SMALL_STATE(12)] = 484,
  [SMALL_STATE(13)] = 526,
  [SMALL_STATE(14)] = 574,
  [SMALL_STATE(15)] = 616,
  [SMALL_STATE(16)] = 658,
  [SMALL_STATE(17)] = 697,
  [SMALL_STATE(18)] = 720,
  [SMALL_STATE(19)] = 743,
  [SMALL_STATE(20)] = 782,
  [SMALL_STATE(21)] = 802,
  [SMALL_STATE(22)] = 822,
  [SMALL_STATE(23)] = 840,
  [SMALL_STATE(24)] = 855,
  [SMALL_STATE(25)] = 872,
  [SMALL_STATE(26)] = 893,
  [SMALL_STATE(27)] = 914,
  [SMALL_STATE(28)] = 933,
  [SMALL_STATE(29)] = 950,
  [SMALL_STATE(30)] = 967,
  [SMALL_STATE(31)] = 984,
  [SMALL_STATE(32)] = 1001,
  [SMALL_STATE(33)] = 1018,
  [SMALL_STATE(34)] = 1039,
  [SMALL_STATE(35)] = 1056,
  [SMALL_STATE(36)] = 1073,
  [SMALL_STATE(37)] = 1090,
  [SMALL_STATE(38)] = 1104,
  [SMALL_STATE(39)] = 1136,
  [SMALL_STATE(40)] = 1156,
  [SMALL_STATE(41)] = 1176,
  [SMALL_STATE(42)] = 1196,
  [SMALL_STATE(43)] = 1212,
  [SMALL_STATE(44)] = 1228,
  [SMALL_STATE(45)] = 1242,
  [SMALL_STATE(46)] = 1258,
  [SMALL_STATE(47)] = 1274,
  [SMALL_STATE(48)] = 1288,
  [SMALL_STATE(49)] = 1302,
  [SMALL_STATE(50)] = 1316,
  [SMALL_STATE(51)] = 1332,
  [SMALL_STATE(52)] = 1346,
  [SMALL_STATE(53)] = 1378,
  [SMALL_STATE(54)] = 1394,
  [SMALL_STATE(55)] = 1408,
  [SMALL_STATE(56)] = 1429,
  [SMALL_STATE(57)] = 1458,
  [SMALL_STATE(58)] = 1471,
  [SMALL_STATE(59)] = 1492,
  [SMALL_STATE(60)] = 1505,
  [SMALL_STATE(61)] = 1518,
  [SMALL_STATE(62)] = 1531,
  [SMALL_STATE(63)] = 1550,
  [SMALL_STATE(64)] = 1579,
  [SMALL_STATE(65)] = 1608,
  [SMALL_STATE(66)] = 1637,
  [SMALL_STATE(67)] = 1656,
  [SMALL_STATE(68)] = 1675,
  [SMALL_STATE(69)] = 1689,
  [SMALL_STATE(70)] = 1702,
  [SMALL_STATE(71)] = 1717,
  [SMALL_STATE(72)] = 1732,
  [SMALL_STATE(73)] = 1742,
  [SMALL_STATE(74)] = 1761,
  [SMALL_STATE(75)] = 1780,
  [SMALL_STATE(76)] = 1792,
  [SMALL_STATE(77)] = 1800,
  [SMALL_STATE(78)] = 1808,
  [SMALL_STATE(79)] = 1816,
  [SMALL_STATE(80)] = 1828,
  [SMALL_STATE(81)] = 1836,
  [SMALL_STATE(82)] = 1848,
  [SMALL_STATE(83)] = 1861,
  [SMALL_STATE(84)] = 1872,
  [SMALL_STATE(85)] = 1883,
  [SMALL_STATE(86)] = 1894,
  [SMALL_STATE(87)] = 1904,
  [SMALL_STATE(88)] = 1914,
  [SMALL_STATE(89)] = 1922,
  [SMALL_STATE(90)] = 1932,
  [SMALL_STATE(91)] = 1940,
  [SMALL_STATE(92)] = 1947,
  [SMALL_STATE(93)] = 1952,
  [SMALL_STATE(94)] = 1959,
  [SMALL_STATE(95)] = 1966,
  [SMALL_STATE(96)] = 1973,
  [SMALL_STATE(97)] = 1980,
  [SMALL_STATE(98)] = 1985,
  [SMALL_STATE(99)] = 1990,
  [SMALL_STATE(100)] = 1995,
  [SMALL_STATE(101)] = 2002,
  [SMALL_STATE(102)] = 2006,
  [SMALL_STATE(103)] = 2010,
  [SMALL_STATE(104)] = 2014,
  [SMALL_STATE(105)] = 2018,
  [SMALL_STATE(106)] = 2022,
  [SMALL_STATE(107)] = 2026,
  [SMALL_STATE(108)] = 2030,
  [SMALL_STATE(109)] = 2034,
  [SMALL_STATE(110)] = 2038,
  [SMALL_STATE(111)] = 2042,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(55),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(100),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(23),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [23] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(38),
  [26] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(7),
  [29] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(10),
  [32] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(73),
  [35] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(55),
  [38] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(100),
  [41] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(23),
  [44] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sequence, 1, 0, 0),
  [46] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_sequence, 1, 0, 0),
  [48] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_sequence_repeat1, 2, 0, 0),
  [50] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_sequence_repeat1, 2, 0, 0), SHIFT_REPEAT(38),
  [53] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_sequence_repeat1, 2, 0, 0), SHIFT_REPEAT(7),
  [56] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_sequence_repeat1, 2, 0, 0), SHIFT_REPEAT(10),
  [59] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_sequence_repeat1, 2, 0, 0), SHIFT_REPEAT(73),
  [62] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_sequence_repeat1, 2, 0, 0), SHIFT_REPEAT(55),
  [65] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_sequence_repeat1, 2, 0, 0), SHIFT_REPEAT(100),
  [68] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_sequence_repeat1, 2, 0, 0),
  [70] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [72] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [74] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [76] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [78] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [80] = {.entry = {.count = 1, .reusable = true}}, SHIFT(93),
  [82] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_sequence_repeat1, 2, 0, 0), SHIFT_REPEAT(52),
  [85] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_sequence_repeat1, 2, 0, 0), SHIFT_REPEAT(13),
  [88] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_sequence_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [91] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_sequence_repeat1, 2, 0, 0), SHIFT_REPEAT(74),
  [94] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_sequence_repeat1, 2, 0, 0), SHIFT_REPEAT(55),
  [97] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_sequence_repeat1, 2, 0, 0), SHIFT_REPEAT(93),
  [100] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_node_pattern, 2, 0, 0),
  [102] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_node_pattern, 2, 0, 0),
  [104] = {.entry = {.count = 1, .reusable = false}}, SHIFT(94),
  [106] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_node_pattern, 3, 0, 0),
  [108] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_node_pattern, 3, 0, 0),
  [110] = {.entry = {.count = 1, .reusable = false}}, SHIFT(91),
  [112] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_disjunction_repeat1, 2, 0, 0),
  [114] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_disjunction_repeat1, 2, 0, 0),
  [116] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pattern_name, 1, 0, 0),
  [118] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pattern_reference, 2, 0, 0),
  [120] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_pattern_reference, 2, 0, 0),
  [122] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_disjunction, 2, 0, 0),
  [124] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [126] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_disjunction, 2, 0, 0),
  [128] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_disjunction, 1, 0, 0),
  [130] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_disjunction, 1, 0, 0),
  [132] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_postfix_term, 1, 0, 0),
  [134] = {.entry = {.count = 1, .reusable = false}}, SHIFT(42),
  [136] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_postfix_term, 1, 0, 0),
  [138] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_primary_term, 3, 0, 0),
  [140] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_primary_term, 3, 0, 0),
  [142] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_name, 1, 0, 0),
  [144] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_name, 1, 0, 0),
  [146] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_node_name, 2, 0, 0),
  [148] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_node_name, 2, 0, 0),
  [150] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_pattern_name, 1, 0, 0),
  [152] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_disjunction_repeat1, 2, 0, 0), SHIFT_REPEAT(16),
  [155] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_conjunction_repeat1, 2, 0, 0),
  [157] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_conjunction_repeat1, 2, 0, 0),
  [159] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_node_pattern, 4, 0, 0),
  [161] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_node_pattern, 4, 0, 0),
  [163] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_primary_term, 1, 0, 0),
  [165] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_primary_term, 1, 0, 0),
  [167] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [169] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [171] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_conjunction, 1, 0, 0),
  [173] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [175] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_conjunction, 1, 0, 0),
  [177] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_conjunction_repeat1, 2, 0, 0), SHIFT_REPEAT(14),
  [180] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_conjunction, 2, 0, 0),
  [182] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_conjunction, 2, 0, 0),
  [184] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_postfix_term, 2, 0, 0),
  [186] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_postfix_term, 2, 0, 0),
  [188] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [190] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_term, 2, 0, 0),
  [192] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_term, 2, 0, 0),
  [194] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_term, 1, 0, 0),
  [196] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_term, 1, 0, 0),
  [198] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [200] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 1, 0, 0),
  [202] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression, 1, 0, 0),
  [204] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_relation_pattern, 1, 0, 0),
  [206] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [208] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [210] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_relation_pattern, 2, 0, 0),
  [212] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_query, 1, 0, 0),
  [214] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [216] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_query, 1, 0, 0),
  [218] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_query, 2, 0, 0),
  [220] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_query, 2, 0, 0),
  [222] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_query_repeat1, 2, 0, 0),
  [224] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_query_repeat1, 2, 0, 0), SHIFT_REPEAT(8),
  [227] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_query_repeat1, 2, 0, 0),
  [229] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pattern_definition, 3, 0, 0),
  [231] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_pattern_definition, 3, 0, 0),
  [233] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_relation_pattern, 3, 0, 0),
  [235] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_relation_label, 1, 0, 0),
  [237] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [239] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [241] = {.entry = {.count = 1, .reusable = true}}, SHIFT(106),
  [243] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [245] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [247] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_edge_name, 2, 0, 0),
  [249] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_disjunction_repeat1, 2, 0, 0), SHIFT_REPEAT(19),
  [252] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_relation_pattern, 4, 0, 0),
  [254] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [256] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_conjunction_repeat1, 2, 0, 0), SHIFT_REPEAT(15),
  [259] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_attributes_repeat1, 2, 0, 0),
  [261] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_attributes_repeat1, 2, 0, 0), SHIFT_REPEAT(82),
  [264] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attributes, 2, 0, 0),
  [266] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [268] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [270] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attributes, 1, 0, 0),
  [272] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [274] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [276] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [278] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_value, 1, 0, 0),
  [280] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute, 3, 0, 0),
  [282] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute, 4, 0, 0),
  [284] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [286] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [288] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [290] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [292] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [294] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_key, 1, 0, 0),
  [296] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [298] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [300] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [302] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_semgrex(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
